// -*- mode:c++;indent-tabs-mode:nil;c-basic-offset:4;coding:utf-8 -*-
// vi: set et ft=cpp ts=4 sts=4 sw=4 fenc=utf-8 :vi
//
// Copyright 2026 Mozilla.ai
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Guards the build-time-generated Unicode codepoint-flags table.
//
// llama.cpp/src/unicode.cpp used to build a 2.23MB per-codepoint flags table
// lazily on first use (1,114,112 scalar stores plus four sparse passes over the
// whitespace/case/NFD tables) - about 3ms in every process that tokenized
// anything. That table is now precomputed into .rodata as
// llama.cpp/src/unicode-data-flags.cpp, generated by
// llamafile/gen_unicode_flags.cpp.
//
// Because the generated file is checked in rather than rebuilt during the
// build, it can silently go stale if unicode-data.cpp is ever regenerated (e.g.
// bumped to a newer Unicode version). This test recomputes the table from the
// checked-in source tables and compares every codepoint against what
// unicode_cpt_flags_from_cpt() actually returns, so staleness - or a bad index
// in the accessor - fails the build instead of silently changing tokenization.
//
// If unicode_cpt_flags_array() in unicode.cpp is ever changed, update the
// reference implementation below to match and regenerate the table.

// Use relative paths: llama.cpp/common/unicode.h (a different, UTF-8 streaming
// helper header) comes earlier in the -iquote search order and would otherwise
// shadow llama.cpp/src/unicode.h. Same hazard llamafile/twizzler.h documents
// for llama.h.
#include "../llama.cpp/src/unicode.h"
#include "../llama.cpp/src/unicode-data.h"

#include <cstdio>
#include <cstdlib>
#include <vector>

// Reference implementation: a verbatim copy of unicode.cpp's (file-static, so
// not reachable from here) unicode_cpt_flags_array().
static std::vector<unicode_cpt_flags> reference_cpt_flags_array() {
    std::vector<unicode_cpt_flags> cpt_flags(MAX_CODEPOINTS, unicode_cpt_flags::UNDEFINED);

    if (unicode_ranges_flags.begin()[0].first != 0) {
        fprintf(stderr, "unicode_flags_test: unicode_ranges_flags does not start at 0\n");
        exit(1);
    }
    if (unicode_ranges_flags.begin()[unicode_ranges_flags.size() - 1].first != MAX_CODEPOINTS) {
        fprintf(stderr, "unicode_flags_test: unicode_ranges_flags does not end at MAX_CODEPOINTS\n");
        exit(1);
    }

    for (size_t i = 1; i < unicode_ranges_flags.size(); ++i) {
        const auto range_ini = unicode_ranges_flags.begin()[i - 1];
        const auto range_end = unicode_ranges_flags.begin()[i];
        for (uint32_t cpt = range_ini.first; cpt < range_end.first; ++cpt) {
            cpt_flags[cpt] = range_ini.second;
        }
    }

    for (auto cpt : unicode_set_whitespace) { cpt_flags[cpt].is_whitespace = true; }
    for (auto p : unicode_map_lowercase)    { cpt_flags[p.second].is_lowercase = true; }
    for (auto p : unicode_map_uppercase)    { cpt_flags[p.second].is_uppercase = true; }
    for (auto & range : unicode_ranges_nfd) { cpt_flags[range.nfd].is_nfd = true; }

    return cpt_flags;
}

int main() {
    static_assert(sizeof(unicode_cpt_flags) == 2, "flags word must stay 2 bytes");

    const std::vector<unicode_cpt_flags> reference = reference_cpt_flags_array();

    int mismatches = 0;
    for (uint32_t cpt = 0; cpt < MAX_CODEPOINTS; ++cpt) {
        const uint16_t want = reference[cpt].as_uint();
        const uint16_t got  = unicode_cpt_flags_from_cpt(cpt).as_uint();
        if (want != got) {
            if (mismatches < 10) {
                fprintf(stderr,
                        "unicode_flags_test: cpt U+%04X: generated 0x%04X != reference 0x%04X\n",
                        cpt, got, want);
            }
            ++mismatches;
        }
    }

    if (mismatches) {
        fprintf(stderr,
                "unicode_flags_test: FAIL - %d/%u codepoints differ.\n"
                "  llama.cpp/src/unicode-data-flags.cpp is stale; regenerate it with\n"
                "  llamafile/gen_unicode_flags.cpp (see the comment at the top of this file).\n",
                mismatches, (unsigned) MAX_CODEPOINTS);
        return 1;
    }

    // Out-of-range codepoints must report UNDEFINED rather than reading past
    // the end of the table.
    if (!unicode_cpt_flags_from_cpt(MAX_CODEPOINTS).is_undefined ||
        !unicode_cpt_flags_from_cpt(0xFFFFFFFFu).is_undefined) {
        fprintf(stderr, "unicode_flags_test: FAIL - out-of-range cpt not reported UNDEFINED\n");
        return 1;
    }

    printf("unicode_flags_test: OK - all %u codepoints match the reference table\n",
           (unsigned) MAX_CODEPOINTS);
    return 0;
}
